spring:
  profiles:
    active: prod
  application:
    name: gus-integration-spring
  cloud:
    compatibility-verifier:
      enabled: false
  cache:
    cache-names: gus-session
    caffeine:
      spec: expireAfterWrite=55m # GUS sesh invalidates after 1 hour, revalidate after 55 mins
  threads:
    virtual:
      enabled: true

resilience4j:
  retry:
    instances:
      gusApi:
        maxAttempts: 3
        waitDuration: 1s
        ignoreExceptions:
          - com.piotrekcieslak.gusintegrationspring.exception.GusNotFoundException
  circuitbreaker:
    instances:
      gusApi:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        ignoreExceptions:
          - com.piotrekcieslak.gusintegrationspring.exception.GusNotFoundException