spring:
  profiles:
    active: prod
  application:
    name: gus-integration-spring
  cloud:
    compatibility-verifier:
      enabled: false
  cache:
    cache-names: gus-session
    caffeine:
      spec: expireAfterWrite=55m # GUS sesh invalidates after 1 hour, revalidate after 55 mins

resilience4j:
  retry:
    instances:
      gusApi:
        maxAttempts: 3
        waitDuration: 1s # Wait 1 sec before retry
        ignoreExceptions:
          - com.piotrekcieslak.gusintegrationspring.exception.GusNotFoundException
  circuitbreaker:
    instances:
      gusApi:
        registerHealthIndicator: true # Actuator for monitoring traffic
        slidingWindowSize: 10
        failureRateThreshold: 50 # If 50% of requests fail, go for safety
        waitDurationInOpenState: 10s # After 10 secs, try to reopen connections
        ignoreExceptions:
          - com.piotrekcieslak.gusintegrationspring.exception.GusNotFoundException